---
title: "Automated Machine Learning with H20 (I)"
author: "Davis Rakhshan"
---


# Compensation Features

What can you deduce about the interaction between Monthly Income and Attrition?

    A) Those that are leaving the company have a higher Monthly Income
    B) That those are staying have a lower Monthly Income
    C) Those that are leaving have a lower Monthly Income
    D) It's difficult to deduce anything based on the visualization

Answer: C

# Compensation Features

What can you deduce about the interaction between Percent Salary Hike and Attrition?

    A) Those that are leaving the company have a higher Percent Salary Hike
    B) Those that are staying have a lower Percent Salary Hike
    C) Those that are leaving have lower Percent Salary Hike
    D) It's difficult to deduce anything based on the visualization

Answer: D, difficult as the plot indicates similar medians and ranges for both groups as well as a significant overlap in the distributions of Percent Salary Hike for both groups.

# Compensation Features

What can you deduce about the interaction between Stock Option Level and Attrition?

    A) Those that are leaving the company have a higher stock option level
    B) Those that are staying have a higher stock option level
    C) It's difficult to deduce anything based on the visualization

Answer: B

# Survey Results

What can you deduce about the interaction between Environment Satisfaction and Attrition?

    A) A higher proportion of those leaving have a low environment satisfaction level
    B) A higher proportion of those leaving have a high environment satisfaction level
    C) It's difficult to deduce anything based on the visualization

Answer: A

# Survey Results

What can you deduce about the interaction between Work Life Balance and Attrition

    A) Those that are leaving have higher density of 2's and 3's
    B) Those that are staying have a higher density of 2's and 3's
    C) Those that are staying have a lower density of 2's and 3's
    D) It's difficult to deduce anything based on the visualization

Answer: B

# Performance Data

What Can you deduce about the interaction between Job Involvement and Attrition?

    A) Those that are leaving have a lower density of 3's and 4's
    B) Those that are leaving have a lower density of 1's and 2's
    C) Those that are staying have a lower density of 2's and 3's
    D) It's difficult to deduce anything based on the visualization

Answer: A

# Work-Life Features

What can you deduce about the interaction between Over Time and Attrition?

    A) The proportion of those leaving that are working Over Time are high compared to those that are not leaving
    B) The proportion of those staying that are working Over Time are high compared to those that are not staying

Answer: A

# Training and Education

What can you deduce about the interaction between Training Times Last Year and Attrition

    A) People that leave tend to have more annual trainings
    B) People that leave tend to have less annual trainings
    C) It's difficult to deduce anything based on the visualization

Answer: B

# Time-Based Features

What can you deduce about the interaction between Years At Company and Attrition

    A) People that leave tend to have more working years at the company
    B) People that leave tend to have less working years at the company
    C) It's difficult to deduce anything based on the visualization

Answer: B

# Time-Based Features

What can you deduce about the interaction between Years Since Last Promotion and Attrition?

    A) Those that are leaving have more years since last promotion than those that are staying
    B) Those that are leaving have fewer years since last promotion than those that are staying
    C) It's difficult to deduce anything based on the visualization
	
Answer: B