project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Machine Learning Fundamentals"
            file: content/01_journal/01_ml_fundamentals.qmd
          - text: "02 Supervised ML - Regression (I)"
            file: content/01_journal/02_supervised_ML_1.qmd
          - text: "03 Supervised ML - Regression (II)"
            file: content/01_journal/03_supervised_ML_2.qmd
          - text: "04 Automated Machine Learning with H20 (I)"
            file: content/01_journal/04_automated_ML_with_H2o_1.qmd
          - text: "05 Automated Machine Learning with H20 (II)"
            file: content/01_journal/05_automated_ML_with_H2o_2.qmd
          - text: "06 Performance Measures"
            file: content/01_journal/06_performance_measures.qmd
          - text: "07 Explaining Black-Box Models With LIME"
            file: content/01_journal/07_explain_black_box_with_lime.qmd
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto